//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Feeds
    {
        public int ID { get; set; }
        public System.TimeSpan Time { get; set; }
        public int FeedID { get; set; }
        public int HabitatsID { get; set; }
    
        public virtual Feeds Feeds { get; set; }
        public virtual Habitats Habitats { get; set; }
    }
}
